# HCC-WCH dataset


data_dir: '${oc.env:DATASET_LOCATION, ./data}/MVI数据/MVI_data'
is_valid_file: "lambda path: path.endswith('.jpg')"
is_valid_label: "lambda path: int(os.path.basename(path).split('.')[0].split('_')[1].replace('M', ''))"
grouped_attribute: "lambda path: os.path.basename(path).split('.')[0].split('_')[0]"
test_split_radio: 0.2
n_folds: 5
fold: 0
seed: 42
# no resampling
transform:
  Resize: 256
  CenterCrop: 224
train_loader:
    batch_size: 32
    num_workers: 4
    pin_memory: true
    persistent_workers: true
val_loader:
    num_workers: 4
    batch_size: 8
test_loader:
    num_workers: 4
    batch_size: 8

  # do resampling to 1x1x1
  #transform:
  #  ResampleNifti:
  #  PermuteDimensions: (2, 0, 1)
  #  PadChannels: 220
  #  Resize:
  #    size: 256
  #  CenterCrop:
  #    size: 224


#  Normalize:
#    mean: [0.485, 0.456, 0.406]
#    std: [0.229, 0.224, 0.225]