# HCC-WCH dataset


data_dir: '${oc.env:DATASET_LOCATION, ./data}/HCC-WCH'
is_valid_file: "lambda path: path.endswith('.nii.gz')"
is_valid_label: "lambda path: int(os.path.basename(path).split('.')[0].rsplit('-', 1)[-1])"
processed_data_save_dir: "hcc_wch"
test_split_radio: 0.2
n_folds: 5
fold: 0
seed: 42
# no resampling
transform:
  NiftiToTensor:
  PadChannels: 88
  Resize: 256
  CenterCrop: 224
target_transform:
  ToTensorWithoutNormalization:
    dtype: long
train_loader:
    batch_size: 16
    num_workers: 4
    pin_memory: true
    persistent_workers: true
val_loader:
    num_workers: 4
    batch_size: 8
test_loader:
    num_workers: 4
    batch_size: 8

  # do resampling to 1x1x1
  #transform:
  #  ResampleNifti:
  #  PermuteDimensions: (2, 0, 1)
  #  PadChannels: 220
  #  Resize:
  #    size: 256
  #  CenterCrop:
  #    size: 224


#  Normalize:
#    mean: [0.485, 0.456, 0.406]
#    std: [0.229, 0.224, 0.225]