# ilab dataset

metadata:
    data_dir: '${oc.env:DATASET_LOCATION, ./data}/MVI数据/ROI_224'
    parser:
        image: "lambda path: path.endswith('.jpg')"
        label: "lambda path: int(os.path.basename(path).split('.')[0].split('_')[0][-1])"
        patient_id: "lambda path: os.path.basename(path).split('.')[0].split('_')[0][:2]"
        model: "lambda path: os.path.basename(path).split('.')[0].split('_')[1]"
        number: "lambda path: os.path.basename(path).split('.')[0].split('_')[2]"
    group_by: ['label', 'patient_id', 'model']
split:
    split_cols: ['patient_id']
    test_split_ratio: 0.1
    n_folds: 10
    shuffle: true
    seed: 42
    save_dir: "roi224/split"
    save_name_dict:
        train: 'train_{0}.csv'  # {0} is a placeholder for fold number
        val: 'val_{0}.csv'
        test: 'test.csv'
    reset_split_index: True  # matters
    # the memory bank should only store train samples
    # indices are reset by order: train, val, test
    # so if input index < model_param.n_samples, it should be train samples
    # if input index > model_param.n_samples, it should be val or internal test samples
    # if input index is None, it should be external test samples
    # it works by:
    # 1. `split_dataset_folds` by param `reset_split_index` in modules/monai_data_module.py
    # 2. `IndexTransformd` in utils/custom_transforms.py
load:
    fold: 0
    dataset: 'Dataset'
    dataset_params:
    transform:
        LoadImaged:
            keys: ['image']
        StackImaged:
            keys: ['image']
        DropSliced:
            key: 'image'
            slice_idx: 1
        ToTensord:
            keys: ['image', 'image_slice']
        IndexTransformd:  # 生成patch的全局索引
            key: 'index'
#        CreateCopyd:
#            keys: ['image', 'image_slice']  # create 'image_copy' and 'image_slice_copy'
        ScaleIntensityd:
            keys: ['image', 'image_slice']
            minv: 0.0
            maxv: 1.0
    load_dir: "roi224/split"
    load_name_dict:
        train: 'train_{0}.csv'  # {0} is a placeholder for fold number
        val: 'val_{0}.csv'
        test: 'test.csv'
loader:
    train_loader:
        shuffle: False
        batch_size: 32
        num_workers: 4
        pin_memory: true
        persistent_workers: true
    val_loader:
        shuffle: False
        num_workers: 4
        batch_size: 32
    test_loader:
        shuffle: False
        num_workers: 4
        batch_size: 32


#  Normalize:
#    mean: [0.485, 0.456, 0.406]
#    std: [0.229, 0.224, 0.225]